### ISSUE TITLE
Adicionar grupo sem nome

### ISSUE THREAD

**Issue by helotanaka** [JotaPeans/fact-project#12]
![Captura de tela 2024-04-25 113604](https://github.com/JotaPeans/fact-project/assets/130470569/58c4253b-9e35-4dff-a0be-7f8ebf864c49)

Se não for inserido algo no input é criado um grupo sem nome.

**Comment by apabsp** [comment]
Bug corrigido. Grupo agora precisa de pelo menos 5 caracteres.
