### ISSUE TITLE
Grupos sobrepõem o popup de deletar

### ISSUE THREAD

**Issue by helotanaka** [JotaPeans/fact-project#17]
![image](https://github.com/JotaPeans/fact-project/assets/130470569/a92d2a7d-e488-4d71-ac15-e0030af24a2a)

**Comment by apabsp** [comment]
Bug corrigido. 
Bastou mudar o z-index da div popover-content.

**Comment by apabsp** [comment]
Bug corrigido.
Bastou mudar o z-index da div popover-content.
