### ISSUE TITLE
erro de carregamento da página principal

### ISSUE THREAD

**Issue by lariisantos** [JotaPeans/fact-project#4]
![image](https://github.com/JotaPeans/fact-project/assets/142417937/499960d5-9887-4493-9440-321ab1d66b68)

erro independente se o grupo existe ou não.

**Comment by apabsp** [comment]
Bug corrigido. 
Para verificar se 'groups' é uma lista vazia, conforme a intenção do código, o Django templates utiliza "if not groups". 
Portanto, o erro estava ocorreu por usar incorretamente a sintaxe do Django.

**Comment by apabsp** [comment]
Bug corrigido.
Para verificar se 'groups' é uma lista vazia, conforme a intenção do código, o Django templates utiliza "if not groups".
Portanto, o erro estava ocorreu por usar incorretamente a sintaxe do Django.
